@startuml
skinparam classAttributeIconSize 0
skinparam linetype ortho

package "com.upb.agripos" {

    package "model" {
        class Product {
            - code : String
            - name : String
            - price : double
            - stock : int
        }

        class Cart {
            - items : List<CartItem>
            + addItem()
            + clear()
        }
        
        class Transaction {
            - id : String
            - date : LocalDateTime
            - total : double
            - items : List<TransactionDetail>
        }
    }

    package "dao" {
        interface ProductDAO {
            + updateStock(String, int) : void
            + findByCode(String) : Product
            + findAll() : List<Product>
        }

        interface TransactionDAO {
            + save(Transaction) : void
            + findById(String) : Transaction
            + saveReturnLog(String, String, int) : void
        }
    }

    package "service" {
        ' Mengurus Logika Belanja Saat Ini
        class CartService {
            - cart : Cart
            - discountStrategy : DiscountStrategy
            + addToCart(Product, qty)
            + checkout(PaymentStrategy)
        }

        ' REVISI: Mengurus Data Historis & Retur
        class TransactionService {
            - transDao : TransactionDAO
            - prodDao : ProductDAO
            + findTransactionById(String) : Transaction
            + processReturn(String, String, int) : void
        }
    }

    package "controller" {
        class TransactionController {
            - cartService : CartService
            - transService : TransactionService
            + handleCheckout()
            + handleReturn() ' <-- Fitur Baru
        }
    }
    
    package "strategy" {
        interface PaymentStrategy
        interface DiscountStrategy
    }
}

' Relations
TransactionController --> CartService
TransactionController --> TransactionService

CartService --> TransactionDAO : save transaction
TransactionService --> TransactionDAO : read/update
TransactionService --> ProductDAO : restock item

ProductDAO ..> Product
TransactionDAO ..> Transaction

@enduml